name: XTM_Memoria_Interna

on:
  schedule:
    - cron: '*/15 * * * *'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout del codigo
        uses: actions/checkout@v2

      - name: Configurar Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'

      - name: Instalar Librerias
        run: pip install pandas requests pytz

      - name: Ejecutar Robot y Guardar Memoria
        run: python actualizar_precios.py

      - name: Guardar Cambios en GitHub
        run: |
          git config --global user.name "XTM-Robot"
          git config --global user.email "bot@xtm.com"
          git add historial.csv index.html
          git commit -m "Robot: Nueva memoria guardada [skip ci]" || exit 0
          git push
