name: XTM_Auto_Update
on:
  schedule:
    - cron: '*/15 * * * *'
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: '3.9'
      - name: Instalacion de Herramientas  # <--- AQUÍ ES EL CAMBIO
        run: pip install pandas requests plotly pytz
      - name: Calculo Matemático
        run: python actualizar_precios.py
      - name: Publicar en la Web
        run: |
          git config --global user.name "XTM-Bot"
          git config --global user.email "bot@xtm.com"
          git add index.html
          git commit -m "Actualización visual XTM" || exit 0
          git push
